import React,{useEffect,useState,useRef} from 'react';
import {businessDate} from '@regi/core';
import {createRoot} from 'react-dom/client';
import './style.css';
import {Purchases,Refunds,Management,Stocktakes,ReceiptCorrections} from './workflows';
import {login,callback,hostedDomain,freshToken,logout} from './auth';
import {Dashboard} from './Dashboard';
import {Icon,type IconName} from './Icon';
import {Table} from './Table';
import {yen} from './presentation';
import {reportPeriod} from './report-period';
import {readApiResponse,networkError} from './api-response';
const initialPeriod=reportPeriod(location.search,import.meta.env.VITE_DEMO_HISTORY_END);
const defaultTenant='10000000-0000-4000-8000-000000000001';
const navigation=['ダッシュボード','商品・価格','発注・入荷','在庫・移動','返品・取引','開局・締め','AI・需要予測','同期状況','管理設定'];
const navigationIcons:IconName[]=['overview','products','orders','inventory','refund','clock','book','sync','settings'];
const pageDescriptions:Record<string,string>={
 '商品・価格':'商品情報から、次の価格まで。登録・予約・CSV取込を一か所で。',
 '発注・入荷':'仕入れの流れを、ひとつに。発注から分納まで、記録をつなぎます。',
 '在庫・移動':'いまある在庫を、正確に。増減・棚卸・店舗間移動を管理します。',
 '返品・取引':'一つひとつの取引に、確かな記録を。返品可能数を確認して、返金へ。',
 '開局・締め':'一日のはじまりと終わりを、すっきり。現金と同期状況を照合します。',
 'AI・需要予測':'データを、判断の味方に。予測・提案・集計を根拠とともに。',
 '同期状況':'店舗と本部の記録をつなぐ。同期位置と要確認の原記録を確認します。',
 '管理設定':'あなたの店舗に、フィットする設定。権限・契約・帳票を一か所で。',
};
function App(){
 const [page,setPage]=useState(new URLSearchParams(location.search).get('page')??'ダッシュボード'),[settings,setSettings]=useState<any>(null),[store,setStore]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[products,setProducts]=useState<any[]>([]),[orders,setOrders]=useState<any[]>([]),[sales,setSales]=useState<any[]>([]),[refunds,setRefunds]=useState<any[]>([]),[shifts,setShifts]=useState<any[]>([]),[exports,setExports]=useState<any[]>([]);
 const [token,setToken]=useState(sessionStorage.getItem('regi-token')??''),[subject,setSubject]=useState(sessionStorage.getItem('regi-dev-subject')??'local-admin');
 const [product,setProduct]=useState({sku:'',name:'',jan:'',price:'',cost:'',taxCode:'standard',stockManaged:true});
 const [quantity,setQuantity]=useState('1'),[supplier,setSupplier]=useState(''),[selected,setSelected]=useState(''),[reason,setReason]=useState(''),[reference,setReference]=useState(''),[target,setTarget]=useState(''),[shiftId,setShiftId]=useState(''),[cash,setCash]=useState('10000'),[question,setQuestion]=useState('売上の傾向を説明'),[metric,setMetric]=useState('sales');
 const [editing,setEditing]=useState<any>(null),[effectiveAt,setEffectiveAt]=useState(''),[pin,setPin]=useState(''),[aiResult,setAiResult]=useState<any>(null),[suggestions,setSuggestions]=useState<any[]>([]),[transfers,setTransfers]=useState<any[]>([]),[reviews,setReviews]=useState<any[]>([]),[included,setIncluded]=useState<Record<string,boolean>>({});
 const [from,setFrom]=useState(initialPeriod.from),[to,setTo]=useState(initialPeriod.to);
 const [exportsOpen,setExportsOpen]=useState(false),[exportPollingError,setExportPollingError]=useState(''),[downloading,setDownloading]=useState('');
 const exportPanel=useRef<HTMLElement>(null);
 const visibleExports=exports.filter(entry=>(entry.store_id??entry.storeId)===store),hasPendingExports=visibleExports.some(entry=>['queued','running'].includes(entry.status));
 const scope=JSON.stringify([page,store,from,to,subject,token]),currentScope=useRef(scope);currentScope.current=scope;
 async function api(path:string,body?:any,method='POST'){
  const authorization=await freshToken(token);
  let response:Response;
  try{response=await fetch(path,{method:body?method:'GET',headers:{'Content-Type':'application/json',...(authorization?{Authorization:`Bearer ${authorization}`}:(import.meta.env.DEV?{'x-tenant-id':sessionStorage.getItem('regi-dev-tenant')??defaultTenant,'x-staff-subject':subject}:{}))},body:body?JSON.stringify(body):undefined});}catch{throw networkError();}
  return readApiResponse(response);
 }
 async function refresh(){
  if(!store)return;
  const paths:Record<string,string>={'ダッシュボード':`/v1/reports/sales?storeId=${store}&from=${from}&to=${to}`,'在庫・移動':`/v1/inventory?storeId=${store}`,'AI・需要予測':`/v1/ai/forecasts?storeId=${store}`,'同期状況':'/v1/sync/changes?cursor=0'};
  const [productRows,orderRows,saleRows,refundRows,shiftRows,exportRows,configuration,transferRows,report,reviewRows]=await Promise.all([api('/v1/products'),api(`/v1/documents/purchase-order?storeId=${store}`),api(`/v1/documents/sale?storeId=${store}`),api(`/v1/documents/refund?storeId=${store}`),api(`/v1/documents/shift?storeId=${store}`),api(`/v1/documents/export?storeId=${store}`),api('/v1/settings'),api(`/v1/documents/transfer?storeId=${store}`),paths[page]?api(paths[page]):null,page==='同期状況'?api(`/v1/sync/reviews?storeId=${store}`):[]]);
  if(scope!==currentScope.current)return;setSettings(configuration);setTransfers(transferRows);setProducts(productRows);setOrders(orderRows);setSales(saleRows);setRefunds(refundRows);setShifts(shiftRows);setExports(exportRows);setData(report);setReviews(reviewRows);
 }
 async function action(callback:()=>Promise<any>){if(busy)return;setBusy(true);setError('');try{await callback();await refresh();}catch(caught:any){setError(caught.message);}finally{setBusy(false);}}
 const post=async(path:string,body:any={})=>{
  const requestedScope=currentScope.current,result=await api(path,{operationId:crypto.randomUUID(),storeId:store,...body});
  if(path==='/v1/exports'&&requestedScope===currentScope.current){setExports(current=>[result,...current.filter(entry=>entry.id!==result.id)]);setExportsOpen(true);setExportPollingError('');requestAnimationFrame(()=>exportPanel.current?.scrollIntoView({block:'start'}));}
  return result;
 };
 async function downloadExport(entry:any){
  if(downloading)return;setDownloading(entry.id);setError('');
  try{
   const authorization=await freshToken(token);let response:Response;
   try{response=await fetch(`/v1/exports/${entry.id}/download`,{headers:authorization?{Authorization:`Bearer ${authorization}`}:(import.meta.env.DEV?{'x-tenant-id':sessionStorage.getItem('regi-dev-tenant')??defaultTenant,'x-staff-subject':subject}:{})});}catch{throw networkError();}
   if(!response.ok){await readApiResponse(response);return;}
   const blob=await response.blob();if(!blob.size)throw new Error('帳票が空です。出力履歴から再作成してください');
   const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`regi-${entry.id}.${entry.body.extension}`;document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);
  }catch(caught:any){setError(caught.message);}finally{setDownloading('');}
 }
 useEffect(()=>{if(hostedDomain&&!token)return;let active=true;api('/v1/settings').then(result=>{if(active){setSettings(result);setStore(new URLSearchParams(location.search).get('storeId')??result.stores[0]?.id??'');}}).catch(caught=>{if(active)setError(caught.message);});return()=>{active=false;};},[token,subject]);
 useEffect(()=>{callback().then(result=>{if(result){setToken(result);sessionStorage.setItem('regi-token',result);}}).catch(caught=>setError(caught.message));},[]);
 useEffect(()=>{refresh().catch(caught=>setError(caught.message));},[page,store,from,to]);
 useEffect(()=>{
  setExportPollingError('');if(!store||!hasPendingExports)return;
  let active=true,timer:number;
  const poll=async()=>{
   try{const result=await api(`/v1/documents/export?storeId=${store}`);if(active&&scope===currentScope.current){setExports(result);setExportPollingError('');}}
   catch(caught:any){if(active&&scope===currentScope.current)setExportPollingError(`${caught.message} 完了状態を再確認しています。通信とサーバーの起動状態を確認してください。`);}
   finally{if(active)timer=window.setTimeout(poll,2000);}
  };
  timer=window.setTimeout(poll,1000);return()=>{active=false;window.clearTimeout(timer);};
 },[scope,hasPendingExports]);
 const productName=(id:string)=>products.find(entry=>entry.id===id)?.name??id;
 const productSelect=<select aria-label="商品" value={selected} onChange={event=>setSelected(event.target.value)}><option value="">商品を選択</option>{products.map(entry=><option key={entry.id} value={entry.id}>{entry.name}</option>)}</select>;
 const storeSelect=<select aria-label="移動先" value={target} onChange={event=>setTarget(event.target.value)}><option value="">移動先店舗</option>{settings?.stores.filter((entry:any)=>entry.id!==store).map((entry:any)=><option key={entry.id} value={entry.id}>{entry.name}</option>)}</select>;
 if(hostedDomain&&!token)return <main className="auth-screen"><section><span className="brand-name">REGI</span><h1>店舗管理にログイン</h1><p>Cognitoでメールアドレスとパスワードを確認します。追加認証の有無は環境の設定に従います。AWSの認証情報はブラウザーへ入力しません。</p><button className="primary" onClick={()=>login().catch(caught=>setError(caught.message))}>ログイン</button>{error&&<p role="alert">{error}</p>}</section></main>;
 return <div className="shell">
  <a className="skip-link" href="#main-content">メインコンテンツへ</a>
  <aside aria-label="本部サイドバー">
   <div className="brand"><span className="brand-mark" aria-hidden="true"><Icon name="store"/></span><div className="brand-copy"><div className="brand-name">REGI</div><small>店舗のための管理ツール</small></div></div>
   <div className="workspace"><span className="workspace-icon"><Icon name="store"/></span><div className="workspace-label">本部管理<small>{settings?.tenant.name??'ログイン待ち'}</small></div></div>
   <div className="nav-label">メニュー <span>店舗・本部の業務管理</span></div>
   <nav aria-label="本部メニュー">{navigation.map((item,index)=><button aria-label={item} aria-current={item===page?'page':undefined} title={item} className={item===page?'active':''} onClick={()=>{setData(null);setPage(item);}} key={item}><Icon name={navigationIcons[index]}/><span className="navigation-text">{item}</span></button>)}</nav>
   <div className="aside-bottom"><div className="plan-label"><i/>REGI Standard</div><small>1法人 / 最大5店舗 / 24か月</small><div className="sidebar-footer"><span className="avatar" aria-hidden="true">R</span><div>商いの記録<small>販売・仕入・在庫をひとつに</small></div></div></div>
  </aside>
  <main id="main-content" tabIndex={-1}><header className="app-header"><div><div className="breadcrumb"><span>REGI</span><span className="separator">/</span><span>本部管理</span></div><h1>{page}</h1></div><div className="header-controls"><span className="online">オンライン管理</span><div className="store-selector"><Icon name="store"/><select disabled={busy} aria-label="店舗" value={store} onChange={event=>setStore(event.target.value)}>{settings?.stores.map((entry:any)=><option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></div><button className="refresh-button" aria-label="更新" disabled={busy} onClick={()=>action(refresh)}><Icon name="sync" className={busy?'refreshing':''}/><span className="refresh-label">更新</span></button></div></header>
  <div className="content" aria-busy={busy}>{error&&<div role="alert" className="error">{error}</div>}{busy&&<div role="status" className="notice">保存中です。同じ操作を重ねずお待ちください。</div>}
  {(settings?.demo?.synthetic||initialPeriod.demoDefault)&&<section className="demo-banner" aria-label="架空データの検証環境"><div><b>デモ環境 · 実在の販売実績ではありません</b><p>{settings?.demo?.synthetic?`${settings.demo.startDay} ～ ${settings.demo.endDay} の${settings.demo.days}日分の架空データ。`:`初期表示は ${initialPeriod.from} ～ ${initialPeriod.to} のデモ期間です。`}今日の売上には過去のデモ売上を含めません。</p></div>{settings?.demo?.synthetic&&<button disabled={busy} onClick={()=>{setFrom(settings.demo.startDay);setTo(settings.demo.endDay);setData(null);setPage('ダッシュボード');}}>デモ期間を表示</button>}</section>}
  {page!=='ダッシュボード'&&<div className="page-intro"><span className="eyebrow">商いの記録</span><h2>{page}</h2><p>{pageDescriptions[page]}</p></div>}
 {page==='ダッシュボード'&&<Dashboard report={data} sales={sales} storeName={settings?.stores.find((entry:any)=>entry.id===store)?.name??''} from={from} to={to} onFromChange={setFrom} onToChange={setTo} onNavigate={setPage}/>}

 {page==='商品・価格'&&<><section><h3>商品登録・価格予約</h3><div className="form-grid">{(['sku','name','jan','price','cost'] as const).map((key,index)=><label key={key}>{['SKU','商品名','JAN','単価（円）','標準原価（円）'][index]}<input value={product[key]} onChange={event=>setProduct({...product,[key]:event.target.value})}/></label>)}<label>税区分<select value={product.taxCode} onChange={event=>setProduct({...product,taxCode:event.target.value})}>{[...new Set<string>(settings?.taxRates.map((entry:any)=>entry.code)??[])].map(code=><option key={code}>{code}</option>)}</select></label><label><input type="checkbox" checked={product.stockManaged} onChange={event=>setProduct({...product,stockManaged:event.target.checked})}/>在庫管理する</label></div><button disabled={busy} className="primary" onClick={()=>action(()=>api(editing?`/v1/products/${editing.id}`:'/v1/products',{operationId:crypto.randomUUID(),...product,jan:product.jan||null,effectiveAt:effectiveAt?new Date(effectiveAt).toISOString():new Date().toISOString(),version:editing?.version},editing?'PATCH':'POST'))}>商品を登録</button><div className="row"><select aria-label="編集商品" value={editing?.id??''} onChange={event=>{const entry=products.find(product=>product.id===event.target.value);setEditing(entry??null);if(entry)setProduct({sku:entry.sku,name:entry.name,jan:entry.jan??'',price:entry.price,cost:entry.cost,taxCode:entry.tax_code,stockManaged:entry.stock_managed});}}><option value="">新規登録</option>{products.map(entry=><option key={entry.id} value={entry.id}>{entry.name}</option>)}</select><label>適用開始日時<input type="datetime-local" value={effectiveAt} onChange={event=>setEffectiveAt(event.target.value)}/></label><label>商品CSV取込<input type="file" accept=".csv" onChange={event=>{const file=event.target.files?.[0];if(file)action(async()=>post('/v1/products/import',{csv:await file.text()}));}}/></label></div><p>CSV見出し: sku,jan,name,price,cost,taxCode,stockManaged（true / false）</p></section><section><h3>商品マスター</h3><Table headers={['SKU','商品名','JAN','税込単価','税率','原価','在庫管理']} rows={products.map(entry=>[entry.sku,entry.name,entry.jan,yen(entry.price),`${entry.rate_bps/100}%`,yen(entry.cost),entry.stock_managed?'対象':'対象外'])}/></section></>}
 {page==='発注・入荷'&&<><Purchases api={api} post={post} action={action} busy={busy} products={products} orders={orders} store={store}/><ReceiptCorrections api={api} post={post} action={action} busy={busy} products={products} orders={orders} store={store}/></>}
 {page==='在庫・移動'&&<><section><h3>在庫増減 / 店舗間移動</h3><div className="row">{productSelect}<input aria-label="数量" type="number" value={quantity} onChange={event=>setQuantity(event.target.value)}/><input placeholder="調整理由" value={reason} onChange={event=>setReason(event.target.value)}/><button disabled={busy} onClick={()=>action(()=>post('/v1/inventory/adjustments',{productId:selected,quantity:Number(quantity),reason}))}>増減を記録</button>{storeSelect}<button disabled={busy} onClick={()=>action(()=>post('/v1/transfers',{toStoreId:target,lines:[{productId:selected,quantity:Number(quantity)}]}))}>出庫</button></div><p>残高の直接上書きは行いません。マイナス在庫は確認・調整対象です。</p></section><Stocktakes api={api} post={post} action={action} busy={busy} products={products} store={store}/><section><h3>店舗間移動</h3>{transfers.map(transfer=><div className="order" key={transfer.id}><span>{transfer.id.slice(0,8)} / {transfer.status}</span>{transfer.status==='transit'&&transfer.body.toStoreId===store&&<button disabled={busy} onClick={()=>action(()=>post(`/v1/transfers/${transfer.id}/receive`))}>移動品を受入</button>}</div>)}<h3>店舗別在庫</h3><Table headers={['商品','数量','警告']} rows={(Array.isArray(data)?data:[]).map(entry=>[productName(entry.product_id),entry.quantity,Number(entry.quantity)<0?'マイナス在庫 / 要調整':'—'])}/></section></>}
 {page==='返品・取引'&&<Refunds api={api} post={post} action={action} busy={busy} products={products} sales={sales} refunds={refunds} shifts={shifts} store={store}/>}
 {page==='開局・締め'&&<><section><h3>端末開局 / 現金 / 店舗日締め</h3><div className="row"><input aria-label="担当者PIN" type="password" placeholder="担当者PIN" value={pin} onChange={event=>setPin(event.target.value)}/><input aria-label="現金額" value={cash} onChange={event=>setCash(event.target.value)}/><button disabled={busy} onClick={()=>action(async()=>{const result=await post('/v1/shifts',{deviceId:settings.devices.find((entry:any)=>entry.store_id===store)?.id,opening:cash,pin});setShiftId(result.id);})}>開局</button><select aria-label="開局記録" value={shiftId} onChange={event=>setShiftId(event.target.value)}><option value="">開局記録を選択</option>{shifts.filter(entry=>entry.status==='open').map(entry=><option key={entry.id} value={entry.id}>{settings?.devices.find((device:any)=>device.id===entry.body.deviceId)?.name} / {new Date(entry.created_at).toLocaleString('ja-JP')}</option>)}</select><input placeholder="現金移動理由" value={reason} onChange={event=>setReason(event.target.value)}/><button disabled={busy} onClick={()=>action(()=>post('/v1/cash-movements',{shiftId,amount:cash,direction:'in',reason}))}>現金入金</button><button disabled={busy||!shiftId} onClick={()=>action(()=>post('/v1/cash-movements',{shiftId,amount:cash,direction:'out',reason}))}>現金出金</button><button disabled={busy} onClick={()=>action(()=>post(`/v1/shifts/${shiftId}/close`,{actual:cash}))}>端末暫定締め</button><button disabled={busy} onClick={()=>action(()=>post('/v1/day-closes',{day:to}))}>店舗日締め確定</button></div></section><section><Table headers={['端末','状態','準備金','実査額','差額']} rows={shifts.map(entry=>[entry.body.deviceId,entry.status,yen(entry.body.opening),entry.body.actual??'—',entry.body.difference??'—'])}/></section></>}
 {page==='AI・需要予測'&&<><section className="strategy-card"><span className="tag">STRATEGY NOTES · 集計の根拠</span><h3>集計を根拠に照会</h3><div className="row"><select value={metric} onChange={event=>setMetric(event.target.value)}>{['sales','payments','profit','inventory','orders'].map(entry=><option key={entry}>{entry}</option>)}</select><input aria-label="AI質問" value={question} onChange={event=>setQuestion(event.target.value)}/><button disabled={busy} onClick={()=>action(async()=>{const result=await post('/v1/ai/query',{metric,question,from,to});setAiResult(result);})}>照会する</button></div><p>日本時間の暦月ごとに5,000回（日報を含む）。入力上限12,000・出力上限2,000トークン。Bedrock未接続時は利用枠を戻します。生成文で集計の数値は書き換えません。</p>{aiResult?.updatedAt&&<p>対象店舗: {settings?.stores.find((entry:any)=>entry.id===aiResult.storeId)?.name??aiResult.storeId} / {aiResult.from} ～ {aiResult.to} / 更新日時: {new Date(aiResult.updatedAt).toLocaleString("ja-JP",{timeZone:"Asia/Tokyo"})}（日本時間） / {aiResult.dataSufficiency} <a href={aiResult.link}>根拠の集計画面へ</a></p>}{aiResult?.explanation&&<p>{aiResult.explanation}</p>}{aiResult?.evidence&&<pre>{JSON.stringify(aiResult.evidence,null,2)}</pre>}</section><section><h3>推奨発注 / 基準在庫設定</h3><div className="row">{productSelect}<input aria-label="基準在庫" type="number" value={quantity} onChange={event=>setQuantity(event.target.value)}/><button disabled={busy} onClick={()=>action(()=>post('/v1/ai/reorder-policy',{productId:selected,baseStock:Number(quantity),safetyStock:3,leadDays:3,minimum:1,multiple:1}))}>基準在庫を設定</button><button disabled={busy} onClick={()=>action(async()=>setSuggestions(await api(`/v1/ai/recommendations?storeId=${store}`)))}>発注推奨を計算</button><input placeholder="仕入先" value={supplier} onChange={event=>setSupplier(event.target.value)}/></div>{suggestions.map(suggestion=><div className="order" key={suggestion.productId}><span>{suggestion.name} / {suggestion.quantity} 個 / {suggestion.method} / {suggestion.updatedAt??'更新記録なし'}</span>{suggestion.quantity>0&&<button disabled={busy} onClick={()=>action(()=>post('/v1/purchase-orders',{supplier,expectedAt:to,lines:[{productId:suggestion.productId,quantity:suggestion.quantity,unitCost:products.find(product=>product.id===suggestion.productId)?.cost??'0'}]}))}>提案から発注下書き</button>}</div>)}<h3>翌7日需要予測</h3><Table headers={['商品','営業日','予測数','方式','更新日時']} rows={(Array.isArray(data)?data:[]).map(entry=>[productName(entry.product_id),entry.day,entry.quantity,entry.method,entry.generated_at])}/><p>履歴不足・精度不足は基準在庫方式。同期未完了日は学習に含めません。</p></section></>}
 {page==='同期状況'&&<><section><h3>要確認イベント / 原記録の管理者再検証</h3><input placeholder="決済結果・原記録照合の承認理由" value={reason} onChange={event=>setReason(event.target.value)}/>{reviews.map(event=><div className="order" key={event.id}><div><b>{event.id}</b><small>{event.result.code} / {event.result.message}</small></div>{['STOCKTAKE_RECONCILE','STOCKTAKE_ACTIVE'].includes(event.result.code)&&<label><input type="checkbox" checked={included[event.id]??false} onChange={change=>setIncluded({...included,[event.id]:change.target.checked})}/>この売上の在庫減少は実査済み数量に含まれる（未チェック=含まれない）</label>}<button disabled={busy} onClick={()=>action(()=>post(`/v1/sync/reviews/${event.id}/retry`,{reason,...(['STOCKTAKE_RECONCILE','STOCKTAKE_ACTIVE'].includes(event.result.code)?{inventoryIncludedInCount:included[event.id]??false}:{})}))}>理由付きで原記録を再検証</button></div>)}<h3>端末同期状態</h3><Table headers={['端末','最終同期','未送信','販売停止']} rows={settings?.devices.map((entry:any)=>[entry.name,entry.last_sync??'未同期',entry.pending,entry.stopped?'停止':'販売可'])??[]}/><p>端末時計ではなく法人コミット順カーソルで差分を取得します。</p><p>現在の同期位置: {data?.cursor??'—'}</p></section></>}
 {page==='管理設定'&&<><section><h3>認証・契約</h3><div className="row">{hostedDomain&&<button onClick={()=>login().catch(caught=>setError(caught.message))}>Cognitoログイン</button>}{import.meta.env.DEV&&<><input aria-label="認証トークン" type="password" placeholder="Cognito ID token" value={token} onChange={event=>{setToken(event.target.value);sessionStorage.setItem('regi-token',event.target.value);}}/><select value={subject} onChange={event=>setSubject(event.target.value)}><option>local-admin</option><option>local-cashier</option></select></>}<button onClick={()=>{logout();setProducts([]);setOrders([]);setSales([]);setRefunds([]);setShifts([]);setExports([]);setData(null);setToken('');sessionStorage.removeItem('regi-token');setSettings(null);}}>ログアウト</button></div><p>ローカル認証は開発サーバーのみ。商用環境は管理者MFA必須です。個人の架空データ検証環境だけ、メールアドレスとパスワードでログインできます。</p><p>契約満了: {settings?.tenant.ends_at} / 価格入力: {settings?.tenant.price_mode}</p><Table headers={['担当者','権限','有効']} rows={settings?.staff.map((entry:any)=>[entry.name,entry.role,entry.active?'有効':'無効'])??[]}/><div className="row"><input placeholder="追加店舗名 / 更新契約番号" value={reason} onChange={event=>setReason(event.target.value)}/><button disabled={busy} onClick={()=>action(()=>post('/v1/settings/store',{name:reason}))}>店舗追加</button><button disabled={busy} onClick={()=>action(()=>post('/v1/settings/renew-contract',{proof:reason}))}>署名付き契約で12か月更新</button></div></section><Management api={api} post={post} action={action} busy={busy} products={products} settings={settings} store={store}/></>}
 <section className="exports" ref={exportPanel}>
  <div className="section-heading"><div className="export-heading"><Icon name="download"/><div><h3>データ・帳票出力</h3><p>店舗の記録を、必要な形式で。</p></div></div><div className="export-actions"><button disabled={busy} onClick={()=>action(()=>post('/v1/exports',{format:'csv'}))}>取引CSVを作成</button><button disabled={busy} onClick={()=>action(()=>post('/v1/exports',{format:'bundle'}))}>CSV・保存帳票一式を作成</button></div></div>
  <details className="export-history" open={exportsOpen} onToggle={event=>setExportsOpen(event.currentTarget.open)}>
   <summary><Icon name="folder"/>出力履歴 <span className="export-count">{visibleExports.length}</span><Icon name="chevron"/></summary>
   <p role="status">{hasPendingExports?'帳票を作成中です。完了状態は自動更新されます。':'作成完了した帳票は、下のダウンロードボタンで保存できます。'} 一式出力はPDF・CSVを含む圧縮ファイルです。</p>
   {exportPollingError&&<p role="alert" className="error">{exportPollingError}</p>}
   {visibleExports.map(entry=><div className="row export-record" data-export-id={entry.id} key={entry.id}>
    <span>{({'csv':'取引CSV','bundle':'CSV・保存帳票一式','purchase-pdf':'発注書PDF','receipt-pdf':'領収書PDF','refund-pdf':'返還伝票PDF'} as Record<string,string>)[entry.body.format]??entry.body.format} / {entry.status==='completed'?'作成完了':entry.body.error?'作成エラー・再試行待ち':entry.status==='running'?'作成中':'作成待ち'}<small>出力番号 {entry.id.slice(0,8)}{entry.created_at?` / ${new Date(entry.created_at).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}`:''}</small></span>
    {entry.status==='completed'&&<button disabled={busy||Boolean(downloading)} onClick={()=>downloadExport(entry)}>{downloading===entry.id?'ダウンロード中…':entry.body.extension==='pdf'?'PDFをダウンロード':entry.body.extension==='csv'?'CSVをダウンロード':'一式をダウンロード'}</button>}
   </div>)}
  </details>
 </section>
 <footer><span><strong>REGI</strong> · 店舗運営を、もっとシンプルに。</span><span>販売・仕入・在庫の一貫管理</span></footer></div></main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
