FROM python:3.11-slim
RUN apt-get update && apt-get install -y --no-install-recommends libgomp1 && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY forecast/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY forecast/ .
USER 65534
ENTRYPOINT ["python","regi_forecast.py"]
